### ISSUE TITLE
Use ADB, OpenCV, and Numpy for cursor manipulation

### ISSUE THREAD

**Issue by starch0** [Solunium/Epic-Seven-E7-Secret-Shop-Refresh#1]
Heyy buddy, i just loved your app and the way handle the independent variables / possible error.

However, I noticed that the current implementation, using pyautogui for cursor manipulation has a limitation. It prevents users from performing other tasks while the autoshop functionality is in progress. I propose a modification using ADB, OpenCV, and Numpy to simulate mouse actions.

Utilizing ADB will allow us to control the emulator remotely. This would eliminate the need for direct cursor manipulation, providing more flexibility to users.

Im here to ask permission to add this to your app or even work together if you want to.

**Comment by Solunium** [comment]
> Heyy buddy, i just loved your app and the way handle the independent variables / possible error.
> 
> However, I noticed that the current implementation, using pyautogui for cursor manipulation has a limitation. It prevents users from performing other tasks while the autoshop functionality is in progress. I propose a modification using ADB, OpenCV, and Numpy to simulate mouse actions.
> 
> Utilizing ADB will allow us to control the emulator remotely. This would eliminate the need for direct cursor manipulation, providing more flexibility to users.
> 
> Im here to ask permission to add this to your app or even work together if you want to.

Hi starch0,

Thank you so much for your kind words and for taking the time to provide valuable feedback on this repo. Even though, I already had plan to incorporate ADB as an option, you are more than welcome to fork this repo and work on that android debug bridge functionality.

**Comment by starch0** [comment]
You got discord? So we can talk abt the project, i have some doubts about it
