### ISSUE TITLE
Issue with Mystic Medals

### ISSUE THREAD

**Issue by side85** [Solunium/Epic-Seven-E7-Secret-Shop-Refresh#3]
It doesn't seem to detect and buy mystic medals but it works with covenant and friendship marks.

**Comment by side85** [comment]
Fixed the issue by replacing the mys.jpg with my own image

**Comment by Solunium** [comment]
Thanks for the heads up! This is the second time that I heard of mystic failing, looks like I need to update 'mystic.jpg'. Just wondering, are you running the program on a laptop?

> Fixed the issue by replacing the mys.jpg with my own image

**Comment by Solunium** [comment]
Just updated 'mystic.jpg', see if that fix the problem

**Comment by side85** [comment]
> Thanks for the heads up! This is the second time that I heard of mystic failing, looks like I need to update 'mystic.jpg'. Just wondering, are you running the program on a laptop?
> 
> > Fixed the issue by replacing the mys.jpg with my own image

Running it on desktop pc and with google play games beta.
