### ISSUE TITLE
Cannot press Start Refresh button

### ISSUE THREAD

**Issue by FEAN9999** [Solunium/Epic-Seven-E7-Secret-Shop-Refresh#4]
![image](https://github.com/Solunium/Epic-Seven-E7-Secret-Shop-Refresh/assets/142230197/6b6482fd-b989-4745-b0f6-0098197b30c1)

OS: Windows 11
Bluestack version: 5.14.21.1004 Pie 64-bit

**Comment by Solunium** [comment]
'Bluestacks App Player' is the window title of latest version of bluestacks. Older version of bluestacks have a different window title.

**Comment by FEAN9999** [comment]
Thank you for your reply. I can press the button with solution above. I think you should consider to add this thing to README, user can config follow the name of emulator.
