### ISSUE TITLE
New pc client

### ISSUE THREAD

**Issue by Solunium** [Solunium/Epic-Seven-E7-Secret-Shop-Refresh#5]
I don’t plan on installing the new PC client, so if you are using this program with that, please comment below to let me know about its compatibility. Thanks!

**Comment by dretheace** [comment]
I just tried it this morning and it doesn't seem to work. I tried to type the window name as labeled in the task manager (game Module) and hit enter. The "Start Refresh" button was not clickable.

**Comment by Solunium** [comment]
> I just tried it this morning and it doesn't seem to work. I tried to type the window name as labeled in the task manager (game Module) and hit enter. The "Start Refresh" button was not clickable.

Have you tried the alternative solution that I have posted in #4 (using label on the window box and hit enter) ?

**Comment by dretheace** [comment]
> > I just tried it this morning and it doesn't seem to work. I tried to type the window name as labeled in the task manager (game Module) and hit enter. The "Start Refresh" button was not clickable.
> 
> Have you tried the alternative solution that I have posted in #4 (using label on the window box and hit enter) ?

Yes I tried just typing in the window name "Epic Seven". The "Start Refresh" button is active and I hit it and nothing happens in the game. I also still have the Google Play Beta version still installed and I am not sure if that is why the button is clickable since they have the same window name. When I click on Start Refresh I see that the window name briefly changes to "Press ESC to stop!" before changing back to SHOP AUTO REFRESH.

**Comment by Solunium** [comment]
@dretheace Hmm, that is interesting. The program probably terminated due the window no longer existing (when it flashes press exit to stop). I think there might be an issue when two windows share the same name. Just wondering, is the pc client window resizable? Also, do you have any issue running the program on google play beta?

**Comment by dretheace** [comment]
> @dretheace Hmm, that is interesting. The program probably terminated due the window no longer existing (when it flashes press ESC to stop). I think there might be an issue when two windows share the same name. Just wondering, is the pc client window resizable? Also, do you have any issue running the program on google play beta?

The PC client window is resizable.

I was able to get the program running on google play beta. I just verified it right now and I am still able to make it work.

**Comment by Solunium** [comment]
@dretheace If you happens to have python install on your pc, you can "pip install pygetwindow" and figure out the window title that way using the code snippet below

```
import pygetwindow as gw

# Get a list of all window titles
windows = gw.getAllTitles()

# Print each window title
for title in windows:
    if title:  # Filter out empty titles
        print(title)
```

**Comment by dretheace** [comment]
@Solunium I don't have python installed I believe. Sorry.

**Comment by Solunium** [comment]
> @Solunium I don't have python installed I believe. Sorry.

No problem at all! Your input has been very helpful in identifying the issue.

**Comment by nscklye** [comment]
@Solunium Here's a print out of the script showing window titles:

```
Windows PowerShell
New pc client · Issue #5 · Solunium/Epic-Seven-E7-Secret-Shop-Refresh · GitHub — Mozilla Firefox
Epic Seven
SHOP AUTO REFRESH
STOVE
```

Also, a console is open with some logs:

```
refresh shop start!
Budget: None
Mouse speed: 0.2
Screenshot speed 0.3

Error code from Windows: 2 - The system cannot find the file specified.
Terminated!
Terminating shop refresh ...
refresh shop start!
Budget: None
Mouse speed: 0.2
Screenshot speed 0.3

Error code from Windows: 5 - Access is denied.
Terminated!
Terminating shop refresh ...
refresh shop start!
Budget: None
Mouse speed: 0.2
Screenshot speed 0.3

Error code from Windows: 5 - Access is denied.
Terminated!
Terminating shop refresh ...
```

Figuring that it's complaining about access, I tried running the exe as admin and that fixed the issue. It's now running and buying bookmarks. I am using Windows 11.

**Comment by Solunium** [comment]
@nscklye Thank you so much for taking the time to investigate and resolve this issue! If it really is just a permission issue, then I will add that to the readme. The program resize the window so that it can match the image better, and it move window to the top left to make sure the entire screen is visible for the mouse to interact (both are intended behaivor). Can you confirm that it still successfully purchase bookmark and mystic bookmark?

@dretheace you can give the above solution a try and see if that fix your issue

**Comment by nscklye** [comment]
@Solunium I ran 2000 ss. It purchased bm 30 times and mystics 4 times. Seems good!

**Comment by dretheace** [comment]
@Solunium yes that solution works for me. Thank you.
