### ISSUE TITLE
Help with creating Executable

### ISSUE THREAD

**Issue by isaacwkm** [Solunium/Epic-Seven-E7-Secret-Shop-Refresh#6]
I'm trying to create an executable so that I can run it as administrator, to use with the PC client.

I followed the steps to make an executable and ran into this error:

> pyinstaller : The term 'pyinstaller' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that 
> the path is correct and try again.

I ran the line of code outlined in step 6 above in the VScode terminal with the directory set to the copied repo.

I have pyinstaller installed following the steps on https://pyinstaller.org/en/stable/ so not sure why its showing that. Any additional detail on how to create an executable would be greatly appreciated <3.
 
I love the tool and have been using it for a long time with an emulator before the PC client release.

**Comment by isaacwkm** [comment]
Found out that I had to add pyinstaller to PATH. Seems to be a thing for Python 3.7 and above.

**Comment by isaacwkm** [comment]
<img width="769" alt="image" src="https://github.com/user-attachments/assets/9ecb1098-783d-4b3b-919e-c775d863d5b8">
after creating executable

**Comment by Solunium** [comment]
@isaacwkm Wait, my bad I think you just need to make sure that the assets folder is in the same directory as the exe that you created
